apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: hendrik-e2e-assignment-
spec:
  
  pipelineRef:
    name: nodejs-pipeline
  
  serviceAccountName: build-bot
  
  params:
    - name: source-repo
      value: https://github.com/HendrikJLoe/hendrik-e2e-app
    - name: image-repo
      value: quay.io/hendrik_loeffel/e2e-assignment
    - name: app-name
      value: hendrik-e2e-assignment
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi